include:
  - https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools/-/raw/main/gsi-port-ci.yml

#variables:
#  ROOTFS_URL: "https://ci.ubports.com/job/ubuntu-touch-rootfs/job/main/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
#  OTA_CHANNEL: "utnext/arm64/android9plus/daily"

image: ubuntu:20.04

#build:
#  tags: [ubports]
#  before_script:
#    - apt update
#    - apt install -y git
#    - ./fetch-kernel-modules-source.sh

#devel-flashable:
#  tags: [ubports]
#  after_script:
#    - apt install zstd
#    - zstd -15 -T0 out/ubuntu.img
#  artifacts:
#    paths:
#      - out/ubuntu.img.zst

