# ofono binder driver configuration for Samsung Galaxy M14 5G (m14x)

[Settings]
Device = /dev/binder
InterfaceType = aidl
extPlugin = generic
ExpectSlots = slot1,slot2
3GLTEHandover = false
MaxNonDataMode = none
useDataProfiles = true
signalStrengthRange=-113,-51
radioInterface = 1.4
# RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND
rilRequestOnSetUdub = 13

[slot1]
path = /slot1
slot = 0

[slot2]
path = /slot2
slot = 1
