# ofono binder driver configuration for Samsung Galaxy M14 5G (m14x)

[Settings]
ExpectSlots = slot1,slot2
3GLTEHandover = false
MaxNonDataMode = none
radioInterface = 1.4
emptyPinQuery = false
useDataProfiles = true
mmsDataProfileId = 1001
# RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND
rilRequestOnSetUdub = 13
signalStrengthRange = -113,-51

[slot1]
path = /slot1
slot = 0

[slot2]
path = /slot2
slot = 1
